# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slacker_id', models.CharField(db_index=True, max_length=20)),
                ('team_id', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=500)),
                ('image_24', models.URLField()),
                ('data', models.TextField()),
            ],
        ),
    ]
