# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUserOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(max_length=10)),
                ('slacker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfrontend.MySlackUser')),
            ],
        ),
    ]
