# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0002_slackuseronline'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuseronline',
            name='team_id',
            field=models.CharField(default='T2F8GMRC2', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slackuseronline',
            name='date_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
