# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0003_auto_20170202_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackuseronline',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='myslackuser',
            name='team_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
