# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0004_auto_20170202_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=20)),
                ('team_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('data', models.TextField()),
            ],
        ),
    ]
