# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0005_slackchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannel',
            name='slacker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webfrontend.MySlackUser'),
            preserve_default=False,
        ),
    ]
