# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0006_slackchannel_slacker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackchannel',
            name='slacker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_slack_oauth.SlackUser'),
        ),
    ]
