# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_oauth', '0005_auto_20161228_2055'),
        ('webfrontend', '0007_auto_20170206_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackchannel',
            old_name='slacker_id',
            new_name='slack_user_access',
        ),
        migrations.RenameField(
            model_name='slackuseronline',
            old_name='slacker_id',
            new_name='my_slack_user',
        ),
        migrations.AddField(
            model_name='myslackuser',
            name='slack_user_access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_slack_oauth.SlackUser'),
            preserve_default=False,
        ),
    ]
