# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0011_auto_20170207_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessage',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='pinned_to',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='reactions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='ts_original',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
