# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontend', '0012_auto_20170207_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackmessage',
            name='pinned_to',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='reactions',
            field=models.TextField(default=None, null=True),
        ),
    ]
